# Data Types In Numpy

In [14]:
"""NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

1.i - integer
2.b - boolean
3.u - unsigned integer
4.f - float
5.c - complex float
6.m - timedelta
7.M - datetime
8.O - object
9.S - string
10.U - unicode string
11.V - fixed chunk of memory for other type ( void )"""


"""ExampleGet your own Python Server
Get the data type of an array object:"""

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)


int32


In [15]:
"""Example
Get the data type of an array containing strings:"""

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


# Creating Arrays With a Defined Data Type

In [16]:
"""Example
Create an array with data type string:"""

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S') #dtype output (|S1) means: S1: String data type with 1 byte per element.

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [17]:
"""Example
Create an array with data type 4 bytes integer:"""

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [20]:
"""Creating an 8-byte Integer Array (dtype='i8' or int64)"""
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [23]:
"""Example
A non integer string like 'a' can not be converted to integer (will raise an error):"""

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')
print(arr.dtype)


ValueError: invalid literal for int() with base 10: 'a'

# Converting Data Type on Existing Arrays

In [26]:
"""
The best way to change the data type of an existing array, is to make a copy of the array with 
the astype() method.
"""

import numpy as np
arr=np.array([1,2,3,4,5])
newarr=arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 2 3 4 5]
int32


In [27]:
"""Example
Change data type from float to integer by using int as parameter value:"""

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
"""Example
Change data type from integer to boolean:"""

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)
