# Joining Array

In [3]:
#  to join to the concatenate() function

import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,5,6])
c= np.concatenate((a,b))
print(c)

[1 2 3 4 4 5 6]


In [4]:
"""Example
Join two 2-D arrays along rows (axis=1):"""

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)  #axis=1 means print column wise (2*4) 

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
"""Example
Join two 2-D arrays along rows (axis=0):"""

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)  #axis=0 means print row wise  (4*2)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#  Using Stack Functions

In [7]:
# to join to the stack() method along with the axis

In [8]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1) #axis=1 column wise

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0) #axis=0 row wise

print(arr)

[[1 2 3]
 [4 5 6]]


# Stacking Along Rows

In [11]:
#  hstack() to stack along rows

In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# Stacking Along Columns

In [13]:
#vstack()  to stack along columns.


In [14]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)
print(


[[[1 4]
  [2 5]
  [3 6]]]
