# normal distribution

In [4]:
# random.normal() method to get a Normal Data Distribution.


In [6]:
from numpy import random

x = random.normal(size=(2, 3)) #row=2 column =3

print(x)

[[-0.03081069  0.72751615 -0.67297723]
 [ 1.51959651  1.35592178 -0.10763183]]


In [7]:
from numpy import random

x = random.normal(loc=1, scale=2, size=(2, 3)) #mean=

print(x)

[[2.78081554 3.47249363 1.1798009 ]
 [1.50733185 1.16687037 1.45746072]]
