# random permutations

In [1]:
# refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

#The NumPy Random module provides two methods for this: shuffle() and permutation()

In [9]:
from numpy import random
import numpy as np
a=np.array([1,2,3,4,5])
random.shuffle(a) #random shuffle every time
print(a)

[5 2 4 3 1]


In [11]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr)) #returns a new array with elements randomly shuffled.


[4 3 2 1 5]


In [12]:
a = np.array([1, 2, 3, 4, 5])
a = a[::-1]  # Reverse the array
print(a)


[5 4 3 2 1]
