# random numbers 

In [5]:
# if limit or value is setting into this it creates random number which is less than one 
arr = np.random.rand(5)  #create 5 random number 
arr

array([0.35404909, 0.0651594 , 0.90466885, 0.17134846, 0.2972832 ])

In [6]:
#two dimensional array 
arr= np.random.rand(3,4) #row =3,column =4
arr

array([[0.76570993, 0.35205626, 0.58472091, 0.02925751],
       [0.00620287, 0.19786024, 0.39324195, 0.76689334],
       [0.98288433, 0.25129463, 0.66539944, 0.63678437]])

In [8]:
#three dimensional array 
arr=np.random.rand(3,4,3) #(divide,row,column)
arr

array([[[0.25682627, 0.34900168, 0.65652479],
        [0.78907353, 0.53178261, 0.5202054 ],
        [0.48459838, 0.44708931, 0.44788736],
        [0.44949461, 0.898503  , 0.31055181]],

       [[0.07451295, 0.25864269, 0.23181971],
        [0.69006144, 0.24032792, 0.68459935],
        [0.04155579, 0.79430279, 0.53730865],
        [0.1609113 , 0.35552856, 0.14990592]],

       [[0.7671959 , 0.5332415 , 0.71920627],
        [0.48201936, 0.05527747, 0.1040797 ],
        [0.13707001, 0.47055404, 0.09522816],
        [0.49059165, 0.22628209, 0.77905247]]])

In [11]:
import numpy as np

arr = np.random.randn(5)  # Generates 5 random numbers from a normal distribution

print(arr)


[-0.11143787  0.3388834  -0.84330284 -0.43959198  0.60947225]


In [12]:
import numpy as np

arr = np.random.randint(0,10,10)  # (start,end,number of element)

print(arr)


[5 4 7 0 7 1 4 6 0 5]


In [13]:
import numpy as np

arr = np.random.randfloat(0,10,10)  # (start,end,number of element)

print(arr)


AttributeError: module 'numpy.random' has no attribute 'randfloat'