# Random Data Distribution

In [1]:
#choice() method allows us to specify the probability for each value.

In [ ]:
#Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

#1.The probability for the value to be 3 is set to be 10%

#2.The probability for the value to be 5 is set to be 30%

#3.The probability for the value to be 7 is set to be 60%

#4.The probability for the value to be 9 is set to be 0%

In [3]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100)) #the number is printed 100 times but number 9 is never included int this array 

print(x)

[7 7 7 7 7 5 5 5 5 5 7 3 7 7 7 5 7 5 7 7 5 7 3 3 7 3 5 7 7 7 7 5 5 5 7 7 7
 5 7 3 7 7 7 5 5 7 5 7 7 5 5 7 5 7 7 5 7 7 5 7 7 7 7 7 3 7 5 5 5 5 7 7 7 7
 3 7 5 7 5 5 5 7 7 7 5 7 5 3 7 7 7 5 7 7 7 5 7 7 7 5]


In [4]:
# two dimensional array

In [6]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5)) #size(row,column) 
#number 9 is never included into this because the probability of number 9 is 0%

print(x)

[[5 3 3 5 7]
 [5 7 5 5 5]
 [7 3 5 7 7]]
