# Searching Arrays

In [9]:
#use the where() method.

In [10]:
"""Example
Find the indexes where the value is 4: """

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


In [11]:
"""Example
Find the indexes where the values are even:"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [13]:
"""Example
Find the indexes where the values are odd:"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


# Search Sorted

In [ ]:
#The searchsorted() method is assumed to be used on sorted arrays.

In [14]:
"""Example
Find the indexes where the value 7 should be inserted:"""

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)


1


# Search From the Right Side

In [15]:
"""Example
Find the indexes where the value 7 should be inserted, starting from the right:"""

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [16]:
"""Example
Find the indexes where the value 7 should be inserted, starting from the left:"""

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='left')

print(x)

1


# Multiple Values

In [17]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
