# slicing arrays 

In [1]:
#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step]

In [3]:
"""Example:
Get your own Python Server
Slice elements from index 1 to index 5 from the following array:"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [4]:
"""Example
Slice elements from index 4 to the end of the array:"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [5]:
"""Example
Slice elements from the beginning to index 4 (not included):"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# Negative slicing

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# step

In [8]:
#print(arr[start:end:gap]
"""Example
Return every other element from index 1 to index 5:"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [9]:
"""Example
Return every other element from the entire array:"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


# Slicing 2-D Arrays

In [10]:
"""Example
From the second element, slice elements from index 1 to index 4 (not included):"""

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [11]:
"""Example
From both elements, return index 2:"""

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [12]:
"""Example
From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:"""

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
