# Simple Arithmetic


# Addition


In [1]:
#The add() function sums the content of two arrays, and return the results in a new array.

In [2]:
import numpy as np
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)


[30 32 34 36 38 40]


# Substraction

In [3]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


# Multiplication

In [4]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


# Division

In [5]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)


[ 3.33333333  4.          3.          5.         25.          1.81818182]


# Power

In [6]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  716276736 -520093696       2500          0]


# Remainder

In [7]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  0  0  0  0 27]


In [8]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.reminder(arr1, arr2)

print(newarr)

AttributeError: module 'numpy' has no attribute 'reminder'