# Chaqnge Shape

In [3]:
import numpy as np

a=np.array([1,2,3,4,5,6])
print("originial array ")
a

b=a.reshape(2,3)  #reshape () is used to reshape the array without changing the data
print("reshape array:")
b

originial array 
reshape array:


array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
for element in b.flat: #flat is used to iterate over or access elements in a multidimensional array
    print(element, end=" ")

print("Element at flat index 0:", b.flat[0])  # First element
print("Element at flat index 5:", b.flat[5])  # Last element


1 2 3 4 5 6 Element at flat index 0: 1
Element at flat index 5: 6


In [12]:
#flatten() method 
c= np.array([[1, 2, 3],
                     [4, 5, 6]])

print("Original 2D Array:")
print(c)

# Use the flatten() method
d = c.flatten()

print("\nFlattened Array:")
d


Original 2D Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:


array([1, 2, 3, 4, 5, 6])

In [13]:
#used to flatten a multi-dimensional array into a 1D array

m = np.array([[7,8,9],
                     [4, 5, 6]])

print("Original 2D Array:")
print(m)

n = m.ravel()

print("\nRaveled Array:")
print(n)


Original 2D Array:
[[7 8 9]
 [4 5 6]]

Raveled Array:
[7 8 9 4 5 6]
