# Array Creation

In [9]:
import numpy as np
a=np.array([1,2,3],dtype='int')
a

array([1, 2, 3])

In [8]:
b=np.zeros((2,2),dtype='float') #each element this array is 0
b

array([[0., 0.],
       [0., 0.]])

In [10]:
c=np.zeros((3,3),dtype='float')  ##each element this array is float
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ones=np.ones((3,3),dtype='int') #each element this array is 1
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
full=np.full((3,3),5) #each element this array is 5
full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [17]:
identity=np.identity(2,dtype='int') #in identify matrix row and columns are same
identity

array([[1, 0],
       [0, 1]])

In [22]:
eye=np.eye(3,3,dtype='int') #k=0 is set in initially
eye

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
eye=np.eye(3,3,1) #when k=1 the element 1 moves one side to the right 
eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [21]:
eye=np.eye(3,3,-1) #when k=1 the element 1 moves one side to the left
eye


array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [24]:
arrange=np.arange(1,10,2) #start =1 ,last=10,range =2
arrange

array([1, 3, 5, 7, 9])

In [25]:
linspace=np.linspace(1,10,10) #start 1,last =10,number =10
linspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
linspace.size #to check the size of it


10

In [27]:
empty=np.empty((1,5)) #creates an uninitialized array with 1 row and 5 columns.
empty

array([[2.12199579e-314, 1.31988138e-311, 8.26077760e-321,
        6.95187041e-310, 0.00000000e+000]])

In [28]:
# Initialize an empty array of size 10
array_data = np.empty(10, dtype='int')
# Use a for loop to populate the array
for i in range(10):
    array_data[i] = i

print(array_data)


[0 1 2 3 4 5 6 7 8 9]
