# Array Indexing And Slicing

# Indexing

In [12]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)


[1 2 3 4 5]


In [13]:
a[0]

1

In [15]:
import numpy as np

b = np.random.randint(1, 10, size=(3, 3))
print(b)


[[5 5 4]
 [6 4 2]
 [5 7 4]]


In [16]:
b[0][1]

5

In [17]:
b[0][0]

5

In [19]:
b[2,1]

7

In [20]:
c = np.random.randint(1, 10, size=(2,3, 3))
print(c)


[[[6 4 7]
  [1 4 4]
  [5 8 7]]

 [[8 6 9]
  [2 9 3]
  [2 7 4]]]


In [21]:
c[0][1][2]

4

In [22]:
c[0][2][1]

8