# Slicing

In [24]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)


[1 2 3 4 5]


In [26]:
print(a[0:3]) #[beginner index: ending index]

[1 2 3]


In [28]:
print(a[2:])

[3 4 5]


In [31]:
import numpy as np

# Creating a 2D array
b = np.array([[1, 2, 3], [4, 5, 6],[9,1,3]])
print(b)


[[1 2 3]
 [4 5 6]
 [9 1 3]]


In [32]:
b[0:2] #[begginer row:ending row]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
b[0:2 ,0:2] #[begginer row,ending row : begginer column,ending column] #column is  selected to cut

array([[1, 2],
       [4, 5]])